### ISSUE TITLE
API unavailable? 

### ISSUE THREAD

**Issue by mander-pander** [zachspiel/bobsburgers-api#1]
@zachspiel  Hello! I was able to access the Bob's Burgers API last night but today it seems to be unavailable. Will you be allowing access to this again? Thank you!

**Comment by zachspiel** [comment]
@mander-pander Hello! I am so sorry about that, there seemed to be an issue with Heroku that caused the server to crash. This issue seems to be resolved now, but I will be looking into other hosting options in the future for better stability. 

Thank you for letting me know!

**Comment by mander-pander** [comment]
Thank you so much for looking into it!
