### ISSUE TITLE
Pest Truck dups

### ISSUE THREAD

**Issue by justinseal** [zachspiel/bobsburgers-api#3]
I noticed the PestTruck end point has about 12 copies of the same first item.

**Comment by zachspiel** [comment]
Sorry about that, I am looking into this issue now. Thanks for letting me know!

**Comment by zachspiel** [comment]
This was actually intentional as every episode in the first season had the same pest control truck in the opening sequence. See: https://bobs-burgers.fandom.com/wiki/Pest_Control_Truck.

This is confusing though, so I will remove the duplicates from the database this weekend.

**Comment by zachspiel** [comment]
Hello, sorry for the delay in responding. I just updated the [documentation](https://www.bobsburgersapi.com/documentation#pest-control-truck) to add a message to inform users that the first 13 trucks are all duplicates.

**Comment by justinseal** [comment]
Thanks! That way others won’t be confused! -JustinOn Jul 24, 2022, at 11:56, Zachary Spielberger ***@***.***> wrote:﻿
Hello, sorry for the delay in responding. I just updated the documentation to add a message to inform users that the first 13 trucks are all duplicates.
